In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math
import seaborn as sns
import sklearn
from sklearn import linear_model
from sklearn import preprocessing
%matplotlib inline
sns.set_style('white')

Using this credit card fraud dataset develop an algorithm to predict fraud. Prioritize correctly finding fraud rather than correctly labeling non-fraudulent transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, ... V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

### Class = 1 for Fraudulent, 0 otherwise

In [5]:
# Random forest

In [6]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier(n_jobs=-1)
X = df.drop('Class', 1)
Y = df['Class']
X = X.dropna(axis=1)

In [7]:
cross_val_score(rfc, X, Y, cv=10)

array([0.1689137 , 0.9989467 , 0.99978933, 0.99919244, 0.999368  ,
       0.99898174, 0.99961376, 0.99947331, 0.99947331, 0.9994382 ])

In [8]:
# very good except for the first one, which was very bad

In [9]:
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9   ...         V20       V21       V22       V23  \
0  0.098698  0.363787   ...    0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425   ...   -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654   ...    0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024   ...   -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739   ...    0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [7]:
from sklearn import neighbors

In [8]:
# Build our model.
knn = neighbors.KNeighborsClassifier(n_neighbors=10)
knn.fit(X, Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [12]:
# try 3-4 different cv numbers, nothing bigger than 15

In [13]:
cross_val_score(knn, X, Y, cv=2)

array([0.01014719, 0.99827251])

In [14]:
cross_val_score(knn, X, Y, cv=10)

array([0.0912155 , 0.28656695, 0.12123872, 0.18861697, 0.19827253,
       0.47801966, 0.33258427, 0.34076545, 0.39195927, 0.99827949])

In [15]:
cross_val_score(knn, X, Y, cv=4)

array([0.02127749, 0.36336058, 0.25615853, 0.9982725 ])

# Decision Tree/Random Forest

In [9]:
CLASS = df['Class']

In [10]:
features = X.columns
rfc.fit(X, Y)
importances = rfc.feature_importances_
indices = np.argsort(importances)

In [11]:
for feature in zip(features, rfc.feature_importances_): 
    print(feature)

('Time', 0.01406296328000175)
('V1', 0.018398113637571736)
('V2', 0.004908778470883305)
('V3', 0.017766023527342176)
('V4', 0.03163173019443992)
('V5', 0.011068912183152464)
('V6', 0.015359328486606965)
('V7', 0.0315475025809116)
('V8', 0.006375793543792499)
('V9', 0.06766707116407536)
('V10', 0.11170016146194621)
('V11', 0.03655592154144509)
('V12', 0.14556885736869965)
('V13', 0.012740338997609915)
('V14', 0.09151300911213998)
('V15', 0.010066230442129087)
('V16', 0.024053148966787875)
('V17', 0.17129579550840665)
('V18', 0.042558836757148444)
('V19', 0.013241893717763572)
('V20', 0.01242836298051447)
('V21', 0.020979577070239896)
('V22', 0.010198065677129258)
('V23', 0.006687084333401742)
('V24', 0.00724976268308377)
('V25', 0.008387726832695)
('V26', 0.02010268751583788)
('V27', 0.009707773908937883)
('V28', 0.010439117925170821)
('Amount', 0.015739430130135065)


In [12]:
df_2 = df[['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9']]

In [13]:
from sklearn import tree

# Packages for rendering our tree.
import pydotplus
import graphviz

# Initialize and train our tree.
decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=1,
    max_depth=4,
)
decision_tree.fit(df_2, CLASS)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=1, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [14]:
cross_dc = cross_val_score(decision_tree, df_2, CLASS, cv=10)

In [15]:
cross_dc

array([0.99824451, 0.99922758, 0.99877111, 0.99824444, 0.99827955,
       0.99831461, 0.99933287, 0.99845506, 0.99870084, 0.99817416])

In [16]:
rfc = ensemble.RandomForestClassifier(n_jobs= -1)
X = df_2
Y = CLASS
X = X.dropna(axis=1)


In [17]:
cross_rf = cross_val_score(rfc, X, Y, cv=10)

In [18]:
cross_rf

array([0.99842005, 0.99873604, 0.99950844, 0.99887644, 0.99856044,
       0.99905197, 0.99961376, 0.99901685, 0.99898174, 0.9991573 ])

In [23]:
# df['Time'] was giving the single, very low cross_val score.  Dropping it improved the results.